version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0:8000
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/web
    expose:
      - "8000"
